image: node:10.18.0

stages:
  - deploy

deploy job:
  stage: deploy
  script:
    - apt-get install rsync
    - echo "$WETRADE_PEM" > "$(pwd)/wetrade.pem"
    - rsync --delete -azvv -e "ssh -i ./wetrade.pem" root@47.75.61.170:/www/wwwroot/system.cangshu360.com/ ./dist/qa/*