image: node:10.18.0

stages:
  - deploy

deploy job:
  stage: deploy
  script:
    - apt-get update -y
    - apt-get -y install rsync
    - echo "$WETRADE_SSH_PEM"
    - cat "$WETRADE_SSH_PEM"
    - rsync --delete -azvv -e "ssh -i $WETRADE_SSH_PEM" ./dist/qa/* root@47.75.61.170:/www/wwwroot/system.cangshu360.com/