image: node:10.8.0

stages:
  - build
  - deploy

stage: build
script:
  - npm install
  - npm run build:qa

stage: deploy
script:
  - echo "$WETRADE_PEM" > "$(pwd)/wetrade.pem"
  - rsync --delete -azvv -e "ssh -i ./wetrade.pem" root@47.75.61.170:/www/wwwroot/system.cangshu360.com/ ./dist/qa/*