image: node:alpine:10.8.0

stages:
  - build
  - deploy

build job:  
  stage: build
  script:
    - npm install
    - npm run build:qa

deploy job:
  stage: deploy
  script:
    - apk --update --no-cache add rsync openssh-client
    - echo "$WETRADE_PEM" > "$(pwd)/wetrade.pem"
    - rsync --delete -azvv -e "ssh -i ./wetrade.pem" root@47.75.61.170:/www/wwwroot/system.cangshu360.com/ ./dist/qa/*